/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SavedBuild = IDL.Record({
  'creator' : IDL.Text,
  'dateSaved' : IDL.Text,
  'buildId' : IDL.Text,
  'buildName' : IDL.Text,
});
export const FavoriteData = IDL.Record({
  'favoritePerks' : IDL.Vec(IDL.Text),
  'favoriteCharacters' : IDL.Vec(IDL.Text),
  'favoriteBuilds' : IDL.Vec(SavedBuild),
});
export const Build = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Text,
  'character' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'survivor' : IDL.Null, 'killer' : IDL.Null }),
  'tips' : IDL.Text,
  'description' : IDL.Text,
  'perks' : IDL.Vec(IDL.Text),
});
export const KillerStats = IDL.Record({
  'noedKills' : IDL.Nat,
  'survivorsHooked' : IDL.Nat,
  'generatorsDefended' : IDL.Nat,
  'endgameKills' : IDL.Nat,
  'evades' : IDL.Nat,
  'basementHooks' : IDL.Nat,
  'chasesInitiated' : IDL.Nat,
  'sluggedSurvivors' : IDL.Nat,
  'downs' : IDL.Nat,
  'survivorsRescued' : IDL.Nat,
});
export const SurvivorStats = IDL.Record({
  'chasesWon' : IDL.Nat,
  'stealthSuccesses' : IDL.Nat,
  'hooks' : IDL.Nat,
  'escapesHatch' : IDL.Nat,
  'generatorsRepaired' : IDL.Nat,
  'palletsStunned' : IDL.Nat,
  'deaths' : IDL.Nat,
  'escapesGate' : IDL.Nat,
  'saves' : IDL.Nat,
  'deathsFirst' : IDL.Nat,
  'deathsEndgame' : IDL.Nat,
  'escapes' : IDL.Nat,
  'totemsCleansed' : IDL.Nat,
  'stealthFailiures' : IDL.Nat,
  'kills' : IDL.Nat,
  'sacrifices' : IDL.Nat,
});
export const Match = IDL.Record({
  'map' : IDL.Text,
  'matchType' : IDL.Variant({ 'survivor' : IDL.Null, 'killer' : IDL.Null }),
  'result' : IDL.Variant({
    'draw' : IDL.Null,
    'loss' : IDL.Null,
    'victory' : IDL.Null,
  }),
  'teammates' : IDL.Vec(IDL.Text),
  'achievements' : IDL.Vec(IDL.Text),
  'matchId' : IDL.Text,
  'perksUsed' : IDL.Vec(IDL.Text),
  'datePlayed' : IDL.Text,
  'killerStats' : IDL.Opt(KillerStats),
  'mainCharacter' : IDL.Text,
  'survivorStats' : IDL.Opt(SurvivorStats),
});
export const MatchHistory = IDL.Record({
  'totalMatches' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'matches' : IDL.Vec(Match),
});
export const UserData = IDL.Record({
  'favorites' : FavoriteData,
  'builds' : IDL.Vec(Build),
  'matchHistory' : MatchHistory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Character = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'uniquePerks' : IDL.Vec(IDL.Text),
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Variant({ 'survivor' : IDL.Null, 'killer' : IDL.Null }),
  'isLicensed' : IDL.Bool,
  'power' : IDL.Text,
  'releaseYear' : IDL.Nat,
});
export const NewsItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'itemType' : IDL.Variant({
    'tip' : IDL.Null,
    'release' : IDL.Null,
    'update' : IDL.Null,
    'generic' : IDL.Null,
  }),
});
export const WikiEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'lastUpdated' : IDL.Text,
  'section' : IDL.Text,
  'author' : IDL.Text,
});
export const Perk = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'usageTips' : IDL.Text,
  'rarity' : IDL.Text,
  'isUnique' : IDL.Bool,
  'characterId' : IDL.Text,
});
export const GameState = IDL.Record({
  'news' : IDL.Vec(NewsItem),
  'characters' : IDL.Vec(Character),
  'wikiEntries' : IDL.Vec(WikiEntry),
  'perks' : IDL.Vec(Perk),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUserData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserData))],
      [],
    ),
  'getCallerData' : IDL.Func([], [UserData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getGlobalData' : IDL.Func([], [GameState], []),
  'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
  'getPerks' : IDL.Func([], [IDL.Vec(Perk)], ['query']),
  'getUserDataByPrincipal' : IDL.Func([IDL.Principal], [UserData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWikiEntries' : IDL.Func([], [IDL.Vec(WikiEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserData' : IDL.Func([UserData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SavedBuild = IDL.Record({
    'creator' : IDL.Text,
    'dateSaved' : IDL.Text,
    'buildId' : IDL.Text,
    'buildName' : IDL.Text,
  });
  const FavoriteData = IDL.Record({
    'favoritePerks' : IDL.Vec(IDL.Text),
    'favoriteCharacters' : IDL.Vec(IDL.Text),
    'favoriteBuilds' : IDL.Vec(SavedBuild),
  });
  const Build = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Text,
    'character' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'survivor' : IDL.Null, 'killer' : IDL.Null }),
    'tips' : IDL.Text,
    'description' : IDL.Text,
    'perks' : IDL.Vec(IDL.Text),
  });
  const KillerStats = IDL.Record({
    'noedKills' : IDL.Nat,
    'survivorsHooked' : IDL.Nat,
    'generatorsDefended' : IDL.Nat,
    'endgameKills' : IDL.Nat,
    'evades' : IDL.Nat,
    'basementHooks' : IDL.Nat,
    'chasesInitiated' : IDL.Nat,
    'sluggedSurvivors' : IDL.Nat,
    'downs' : IDL.Nat,
    'survivorsRescued' : IDL.Nat,
  });
  const SurvivorStats = IDL.Record({
    'chasesWon' : IDL.Nat,
    'stealthSuccesses' : IDL.Nat,
    'hooks' : IDL.Nat,
    'escapesHatch' : IDL.Nat,
    'generatorsRepaired' : IDL.Nat,
    'palletsStunned' : IDL.Nat,
    'deaths' : IDL.Nat,
    'escapesGate' : IDL.Nat,
    'saves' : IDL.Nat,
    'deathsFirst' : IDL.Nat,
    'deathsEndgame' : IDL.Nat,
    'escapes' : IDL.Nat,
    'totemsCleansed' : IDL.Nat,
    'stealthFailiures' : IDL.Nat,
    'kills' : IDL.Nat,
    'sacrifices' : IDL.Nat,
  });
  const Match = IDL.Record({
    'map' : IDL.Text,
    'matchType' : IDL.Variant({ 'survivor' : IDL.Null, 'killer' : IDL.Null }),
    'result' : IDL.Variant({
      'draw' : IDL.Null,
      'loss' : IDL.Null,
      'victory' : IDL.Null,
    }),
    'teammates' : IDL.Vec(IDL.Text),
    'achievements' : IDL.Vec(IDL.Text),
    'matchId' : IDL.Text,
    'perksUsed' : IDL.Vec(IDL.Text),
    'datePlayed' : IDL.Text,
    'killerStats' : IDL.Opt(KillerStats),
    'mainCharacter' : IDL.Text,
    'survivorStats' : IDL.Opt(SurvivorStats),
  });
  const MatchHistory = IDL.Record({
    'totalMatches' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'matches' : IDL.Vec(Match),
  });
  const UserData = IDL.Record({
    'favorites' : FavoriteData,
    'builds' : IDL.Vec(Build),
    'matchHistory' : MatchHistory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Character = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'uniquePerks' : IDL.Vec(IDL.Text),
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Variant({ 'survivor' : IDL.Null, 'killer' : IDL.Null }),
    'isLicensed' : IDL.Bool,
    'power' : IDL.Text,
    'releaseYear' : IDL.Nat,
  });
  const NewsItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'itemType' : IDL.Variant({
      'tip' : IDL.Null,
      'release' : IDL.Null,
      'update' : IDL.Null,
      'generic' : IDL.Null,
    }),
  });
  const WikiEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'lastUpdated' : IDL.Text,
    'section' : IDL.Text,
    'author' : IDL.Text,
  });
  const Perk = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'usageTips' : IDL.Text,
    'rarity' : IDL.Text,
    'isUnique' : IDL.Bool,
    'characterId' : IDL.Text,
  });
  const GameState = IDL.Record({
    'news' : IDL.Vec(NewsItem),
    'characters' : IDL.Vec(Character),
    'wikiEntries' : IDL.Vec(WikiEntry),
    'perks' : IDL.Vec(Perk),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUserData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserData))],
        [],
      ),
    'getCallerData' : IDL.Func([], [UserData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getGlobalData' : IDL.Func([], [GameState], []),
    'getNews' : IDL.Func([], [IDL.Vec(NewsItem)], ['query']),
    'getPerks' : IDL.Func([], [IDL.Vec(Perk)], ['query']),
    'getUserDataByPrincipal' : IDL.Func([IDL.Principal], [UserData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWikiEntries' : IDL.Func([], [IDL.Vec(WikiEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserData' : IDL.Func([UserData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };