/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Build {
  'id' : string,
  'creator' : string,
  'character' : string,
  'name' : string,
  'role' : { 'survivor' : null } |
    { 'killer' : null },
  'tips' : string,
  'description' : string,
  'perks' : Array<string>,
}
export interface Character {
  'id' : string,
  'bio' : string,
  'uniquePerks' : Array<string>,
  'difficulty' : string,
  'name' : string,
  'role' : { 'survivor' : null } |
    { 'killer' : null },
  'isLicensed' : boolean,
  'power' : string,
  'releaseYear' : bigint,
}
export interface FavoriteData {
  'favoritePerks' : Array<string>,
  'favoriteCharacters' : Array<string>,
  'favoriteBuilds' : Array<SavedBuild>,
}
export interface GameState {
  'news' : Array<NewsItem>,
  'characters' : Array<Character>,
  'wikiEntries' : Array<WikiEntry>,
  'perks' : Array<Perk>,
}
export interface KillerStats {
  'noedKills' : bigint,
  'survivorsHooked' : bigint,
  'generatorsDefended' : bigint,
  'endgameKills' : bigint,
  'evades' : bigint,
  'basementHooks' : bigint,
  'chasesInitiated' : bigint,
  'sluggedSurvivors' : bigint,
  'downs' : bigint,
  'survivorsRescued' : bigint,
}
export interface Match {
  'map' : string,
  'matchType' : { 'survivor' : null } |
    { 'killer' : null },
  'result' : { 'draw' : null } |
    { 'loss' : null } |
    { 'victory' : null },
  'teammates' : Array<string>,
  'achievements' : Array<string>,
  'matchId' : string,
  'perksUsed' : Array<string>,
  'datePlayed' : string,
  'killerStats' : [] | [KillerStats],
  'mainCharacter' : string,
  'survivorStats' : [] | [SurvivorStats],
}
export interface MatchHistory {
  'totalMatches' : bigint,
  'totalScore' : bigint,
  'matches' : Array<Match>,
}
export interface NewsItem {
  'id' : string,
  'title' : string,
  'publishedAt' : string,
  'description' : string,
  'author' : string,
  'itemType' : { 'tip' : null } |
    { 'release' : null } |
    { 'update' : null } |
    { 'generic' : null },
}
export interface Perk {
  'id' : string,
  'name' : string,
  'description' : string,
  'usageTips' : string,
  'rarity' : string,
  'isUnique' : boolean,
  'characterId' : string,
}
export interface SavedBuild {
  'creator' : string,
  'dateSaved' : string,
  'buildId' : string,
  'buildName' : string,
}
export interface SurvivorStats {
  'chasesWon' : bigint,
  'stealthSuccesses' : bigint,
  'hooks' : bigint,
  'escapesHatch' : bigint,
  'generatorsRepaired' : bigint,
  'palletsStunned' : bigint,
  'deaths' : bigint,
  'escapesGate' : bigint,
  'saves' : bigint,
  'deathsFirst' : bigint,
  'deathsEndgame' : bigint,
  'escapes' : bigint,
  'totemsCleansed' : bigint,
  'stealthFailiures' : bigint,
  'kills' : bigint,
  'sacrifices' : bigint,
}
export interface UserData {
  'favorites' : FavoriteData,
  'builds' : Array<Build>,
  'matchHistory' : MatchHistory,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WikiEntry {
  'id' : string,
  'title' : string,
  'content' : string,
  'lastUpdated' : string,
  'section' : string,
  'author' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserData' : ActorMethod<[], Array<[Principal, UserData]>>,
  'getCallerData' : ActorMethod<[], UserData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacters' : ActorMethod<[], Array<Character>>,
  'getGlobalData' : ActorMethod<[], GameState>,
  'getNews' : ActorMethod<[], Array<NewsItem>>,
  'getPerks' : ActorMethod<[], Array<Perk>>,
  'getUserDataByPrincipal' : ActorMethod<[Principal], UserData>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWikiEntries' : ActorMethod<[], Array<WikiEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserData' : ActorMethod<[UserData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];