/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MatchHistory {
    totalMatches: bigint;
    totalScore: bigint;
    matches: Array<Match>;
}
export interface Perk {
    id: string;
    name: string;
    description: string;
    usageTips: string;
    rarity: string;
    isUnique: boolean;
    characterId: string;
}
export interface FavoriteData {
    favoritePerks: Array<string>;
    favoriteCharacters: Array<string>;
    favoriteBuilds: Array<SavedBuild>;
}
export interface KillerStats {
    noedKills: bigint;
    survivorsHooked: bigint;
    generatorsDefended: bigint;
    endgameKills: bigint;
    evades: bigint;
    basementHooks: bigint;
    chasesInitiated: bigint;
    sluggedSurvivors: bigint;
    downs: bigint;
    survivorsRescued: bigint;
}
export interface WikiEntry {
    id: string;
    title: string;
    content: string;
    lastUpdated: string;
    section: string;
    author: string;
}
export interface GameState {
    news: Array<NewsItem>;
    characters: Array<Character>;
    wikiEntries: Array<WikiEntry>;
    perks: Array<Perk>;
}
export interface Character {
    id: string;
    bio: string;
    uniquePerks: Array<string>;
    difficulty: string;
    name: string;
    role: Variant_survivor_killer;
    isLicensed: boolean;
    power: string;
    releaseYear: bigint;
}
export interface SavedBuild {
    creator: string;
    dateSaved: string;
    buildId: string;
    buildName: string;
}
export interface SurvivorStats {
    chasesWon: bigint;
    stealthSuccesses: bigint;
    hooks: bigint;
    escapesHatch: bigint;
    generatorsRepaired: bigint;
    palletsStunned: bigint;
    deaths: bigint;
    escapesGate: bigint;
    saves: bigint;
    deathsFirst: bigint;
    deathsEndgame: bigint;
    escapes: bigint;
    totemsCleansed: bigint;
    stealthFailiures: bigint;
    kills: bigint;
    sacrifices: bigint;
}
export interface Match {
    map: string;
    matchType: Variant_survivor_killer;
    result: Variant_draw_loss_victory;
    teammates: Array<string>;
    achievements: Array<string>;
    matchId: string;
    perksUsed: Array<string>;
    datePlayed: string;
    killerStats?: KillerStats;
    mainCharacter: string;
    survivorStats?: SurvivorStats;
}
export interface UserData {
    favorites: FavoriteData;
    builds: Array<Build>;
    matchHistory: MatchHistory;
}
export interface NewsItem {
    id: string;
    title: string;
    publishedAt: string;
    description: string;
    author: string;
    itemType: Variant_tip_release_update_generic;
}
export interface Build {
    id: string;
    creator: string;
    character: string;
    name: string;
    role: Variant_survivor_killer;
    tips: string;
    description: string;
    perks: Array<string>;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_draw_loss_victory {
    draw = "draw",
    loss = "loss",
    victory = "victory"
}
export enum Variant_survivor_killer {
    survivor = "survivor",
    killer = "killer"
}
export enum Variant_tip_release_update_generic {
    tip = "tip",
    release = "release",
    update = "update",
    generic = "generic"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllUserData(): Promise<Array<[Principal, UserData]>>;
    getCallerData(): Promise<UserData>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCharacters(): Promise<Array<Character>>;
    getGlobalData(): Promise<GameState>;
    getNews(): Promise<Array<NewsItem>>;
    getPerks(): Promise<Array<Perk>>;
    getUserDataByPrincipal(principal: Principal): Promise<UserData>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWikiEntries(): Promise<Array<WikiEntry>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveUserData(data: UserData): Promise<void>;
}
import type { Build as _Build, Character as _Character, FavoriteData as _FavoriteData, GameState as _GameState, KillerStats as _KillerStats, Match as _Match, MatchHistory as _MatchHistory, NewsItem as _NewsItem, Perk as _Perk, SurvivorStats as _SurvivorStats, UserData as _UserData, UserProfile as _UserProfile, UserRole as _UserRole, WikiEntry as _WikiEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllUserData(): Promise<Array<[Principal, UserData]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserData();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserData();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerData(): Promise<UserData> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerData();
                return from_candid_UserData_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerData();
            return from_candid_UserData_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacters(): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacters();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacters();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalData(): Promise<GameState> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalData();
                return from_candid_GameState_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalData();
            return from_candid_GameState_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNews(): Promise<Array<NewsItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPerks(): Promise<Array<Perk>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPerks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPerks();
            return result;
        }
    }
    async getUserDataByPrincipal(arg0: Principal): Promise<UserData> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDataByPrincipal(arg0);
                return from_candid_UserData_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDataByPrincipal(arg0);
            return from_candid_UserData_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWikiEntries(): Promise<Array<WikiEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWikiEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWikiEntries();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveUserData(arg0: UserData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserData(to_candid_UserData_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserData(to_candid_UserData_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Build_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Build): Build {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Character_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Character): Character {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_MatchHistory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchHistory): MatchHistory {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_NewsItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsItem): NewsItem {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserData_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserData): UserData {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KillerStats]): KillerStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SurvivorStats]): SurvivorStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMatches: bigint;
    totalScore: bigint;
    matches: Array<_Match>;
}): {
    totalMatches: bigint;
    totalScore: bigint;
    matches: Array<Match>;
} {
    return {
        totalMatches: value.totalMatches,
        totalScore: value.totalScore,
        matches: from_candid_vec_n13(_uploadFile, _downloadFile, value.matches)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    map: string;
    matchType: {
        survivor: null;
    } | {
        killer: null;
    };
    result: {
        draw: null;
    } | {
        loss: null;
    } | {
        victory: null;
    };
    teammates: Array<string>;
    achievements: Array<string>;
    matchId: string;
    perksUsed: Array<string>;
    datePlayed: string;
    killerStats: [] | [_KillerStats];
    mainCharacter: string;
    survivorStats: [] | [_SurvivorStats];
}): {
    map: string;
    matchType: Variant_survivor_killer;
    result: Variant_draw_loss_victory;
    teammates: Array<string>;
    achievements: Array<string>;
    matchId: string;
    perksUsed: Array<string>;
    datePlayed: string;
    killerStats?: KillerStats;
    mainCharacter: string;
    survivorStats?: SurvivorStats;
} {
    return {
        map: value.map,
        matchType: from_candid_variant_n10(_uploadFile, _downloadFile, value.matchType),
        result: from_candid_variant_n16(_uploadFile, _downloadFile, value.result),
        teammates: value.teammates,
        achievements: value.achievements,
        matchId: value.matchId,
        perksUsed: value.perksUsed,
        datePlayed: value.datePlayed,
        killerStats: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.killerStats)),
        mainCharacter: value.mainCharacter,
        survivorStats: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.survivorStats))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    uniquePerks: Array<string>;
    difficulty: string;
    name: string;
    role: {
        survivor: null;
    } | {
        killer: null;
    };
    isLicensed: boolean;
    power: string;
    releaseYear: bigint;
}): {
    id: string;
    bio: string;
    uniquePerks: Array<string>;
    difficulty: string;
    name: string;
    role: Variant_survivor_killer;
    isLicensed: boolean;
    power: string;
    releaseYear: bigint;
} {
    return {
        id: value.id,
        bio: value.bio,
        uniquePerks: value.uniquePerks,
        difficulty: value.difficulty,
        name: value.name,
        role: from_candid_variant_n10(_uploadFile, _downloadFile, value.role),
        isLicensed: value.isLicensed,
        power: value.power,
        releaseYear: value.releaseYear
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    news: Array<_NewsItem>;
    characters: Array<_Character>;
    wikiEntries: Array<_WikiEntry>;
    perks: Array<_Perk>;
}): {
    news: Array<NewsItem>;
    characters: Array<Character>;
    wikiEntries: Array<WikiEntry>;
    perks: Array<Perk>;
} {
    return {
        news: from_candid_vec_n27(_uploadFile, _downloadFile, value.news),
        characters: from_candid_vec_n22(_uploadFile, _downloadFile, value.characters),
        wikiEntries: value.wikiEntries,
        perks: value.perks
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    publishedAt: string;
    description: string;
    author: string;
    itemType: {
        tip: null;
    } | {
        release: null;
    } | {
        update: null;
    } | {
        generic: null;
    };
}): {
    id: string;
    title: string;
    publishedAt: string;
    description: string;
    author: string;
    itemType: Variant_tip_release_update_generic;
} {
    return {
        id: value.id,
        title: value.title,
        publishedAt: value.publishedAt,
        description: value.description,
        author: value.author,
        itemType: from_candid_variant_n30(_uploadFile, _downloadFile, value.itemType)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favorites: _FavoriteData;
    builds: Array<_Build>;
    matchHistory: _MatchHistory;
}): {
    favorites: FavoriteData;
    builds: Array<Build>;
    matchHistory: MatchHistory;
} {
    return {
        favorites: value.favorites,
        builds: from_candid_vec_n7(_uploadFile, _downloadFile, value.builds),
        matchHistory: from_candid_MatchHistory_n11(_uploadFile, _downloadFile, value.matchHistory)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: string;
    character: string;
    name: string;
    role: {
        survivor: null;
    } | {
        killer: null;
    };
    tips: string;
    description: string;
    perks: Array<string>;
}): {
    id: string;
    creator: string;
    character: string;
    name: string;
    role: Variant_survivor_killer;
    tips: string;
    description: string;
    perks: Array<string>;
} {
    return {
        id: value.id,
        creator: value.creator,
        character: value.character,
        name: value.name,
        role: from_candid_variant_n10(_uploadFile, _downloadFile, value.role),
        tips: value.tips,
        description: value.description,
        perks: value.perks
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserData]): [Principal, UserData] {
    return [
        value[0],
        from_candid_UserData_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    survivor: null;
} | {
    killer: null;
}): Variant_survivor_killer {
    return "survivor" in value ? Variant_survivor_killer.survivor : "killer" in value ? Variant_survivor_killer.killer : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    draw: null;
} | {
    loss: null;
} | {
    victory: null;
}): Variant_draw_loss_victory {
    return "draw" in value ? Variant_draw_loss_victory.draw : "loss" in value ? Variant_draw_loss_victory.loss : "victory" in value ? Variant_draw_loss_victory.victory : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tip: null;
} | {
    release: null;
} | {
    update: null;
} | {
    generic: null;
}): Variant_tip_release_update_generic {
    return "tip" in value ? Variant_tip_release_update_generic.tip : "release" in value ? Variant_tip_release_update_generic.release : "update" in value ? Variant_tip_release_update_generic.update : "generic" in value ? Variant_tip_release_update_generic.generic : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Character>): Array<Character> {
    return value.map((x)=>from_candid_Character_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsItem>): Array<NewsItem> {
    return value.map((x)=>from_candid_NewsItem_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserData]>): Array<[Principal, UserData]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Build>): Array<Build> {
    return value.map((x)=>from_candid_Build_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Build_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Build): _Build {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_MatchHistory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchHistory): _MatchHistory {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_Match_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Match): _Match {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserData_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserData): _UserData {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favorites: FavoriteData;
    builds: Array<Build>;
    matchHistory: MatchHistory;
}): {
    favorites: _FavoriteData;
    builds: Array<_Build>;
    matchHistory: _MatchHistory;
} {
    return {
        favorites: value.favorites,
        builds: to_candid_vec_n33(_uploadFile, _downloadFile, value.builds),
        matchHistory: to_candid_MatchHistory_n37(_uploadFile, _downloadFile, value.matchHistory)
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: string;
    character: string;
    name: string;
    role: Variant_survivor_killer;
    tips: string;
    description: string;
    perks: Array<string>;
}): {
    id: string;
    creator: string;
    character: string;
    name: string;
    role: {
        survivor: null;
    } | {
        killer: null;
    };
    tips: string;
    description: string;
    perks: Array<string>;
} {
    return {
        id: value.id,
        creator: value.creator,
        character: value.character,
        name: value.name,
        role: to_candid_variant_n36(_uploadFile, _downloadFile, value.role),
        tips: value.tips,
        description: value.description,
        perks: value.perks
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalMatches: bigint;
    totalScore: bigint;
    matches: Array<Match>;
}): {
    totalMatches: bigint;
    totalScore: bigint;
    matches: Array<_Match>;
} {
    return {
        totalMatches: value.totalMatches,
        totalScore: value.totalScore,
        matches: to_candid_vec_n39(_uploadFile, _downloadFile, value.matches)
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    map: string;
    matchType: Variant_survivor_killer;
    result: Variant_draw_loss_victory;
    teammates: Array<string>;
    achievements: Array<string>;
    matchId: string;
    perksUsed: Array<string>;
    datePlayed: string;
    killerStats?: KillerStats;
    mainCharacter: string;
    survivorStats?: SurvivorStats;
}): {
    map: string;
    matchType: {
        survivor: null;
    } | {
        killer: null;
    };
    result: {
        draw: null;
    } | {
        loss: null;
    } | {
        victory: null;
    };
    teammates: Array<string>;
    achievements: Array<string>;
    matchId: string;
    perksUsed: Array<string>;
    datePlayed: string;
    killerStats: [] | [_KillerStats];
    mainCharacter: string;
    survivorStats: [] | [_SurvivorStats];
} {
    return {
        map: value.map,
        matchType: to_candid_variant_n36(_uploadFile, _downloadFile, value.matchType),
        result: to_candid_variant_n42(_uploadFile, _downloadFile, value.result),
        teammates: value.teammates,
        achievements: value.achievements,
        matchId: value.matchId,
        perksUsed: value.perksUsed,
        datePlayed: value.datePlayed,
        killerStats: value.killerStats ? candid_some(value.killerStats) : candid_none(),
        mainCharacter: value.mainCharacter,
        survivorStats: value.survivorStats ? candid_some(value.survivorStats) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_survivor_killer): {
    survivor: null;
} | {
    killer: null;
} {
    return value == Variant_survivor_killer.survivor ? {
        survivor: null
    } : value == Variant_survivor_killer.killer ? {
        killer: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_draw_loss_victory): {
    draw: null;
} | {
    loss: null;
} | {
    victory: null;
} {
    return value == Variant_draw_loss_victory.draw ? {
        draw: null
    } : value == Variant_draw_loss_victory.loss ? {
        loss: null
    } : value == Variant_draw_loss_victory.victory ? {
        victory: null
    } : value;
}
function to_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Build>): Array<_Build> {
    return value.map((x)=>to_candid_Build_n34(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Match>): Array<_Match> {
    return value.map((x)=>to_candid_Match_n40(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
